### ISSUE TITLE
MythicMobs Item and Mob integration

### ISSUE THREAD

**Issue by EHAndrew** [CoolLord22/OtherDrops1.13#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Integration with the MythicMobs plugin. The ability to use MythicMobs Items and Mobs as drops and tools.

**Describe alternatives you've considered**
I have not considered any alternatives, as the feature does not yet exist in any plugin.

**Comment by CoolLord22** [comment]
Support for MythicMobs is now done! Mythic Mobs and Items can now be referenced as targets, tools, and even drops. See example code below for all usage details :)

```yaml
# Usage for MythicMob as a target
    MYTHIC_MOB@SkeletalKnight:
      - trigger: RIGHT_CLICK
        message: "&aClicked a MythicMob!"
```
```yaml
# Usage for MythicMob as a tool/agent to trigger a drop
    PLAYER:
      - trigger: HIT
        tool: MYTHIC_MOB@SkeletalKnight
        message.victim: "&cYou were hit by a MythicMob!"
```
```yaml
# Usage for dropping MythicItems
    MYTHIC_MOB@SkeletalKnight:
      - trigger: RIGHT_CLICK
        message: "&aThe knight gave you a mythical sword!"
        drop: MYTHIC_ITEM@SkeletonKingSword
```
```yaml
# Usage for spawning MythicMobs
    PLAYER:
      - trigger: HIT
        drop: MYTHIC_MOB@SkeletalKnight
        message.victim: "&cYou were damaged and spawned a MythicMob!"
```
```yaml
# Usage for MythicMobs item as a tool
    ANY_BLOCK:
      - trigger: RIGHT_CLICK
        tool: MYTHIC_ITEM@SkeletonKingSword
        message: "&aSuccessfully clicked with a mythic item!"
```
