### ISSUE TITLE
Composter does not inherit level data by default

### ISSUE THREAD

**Issue by CoolLord22** [CoolLord22/OtherDrops1.13#33]
**Describe the bug**
Originally reported by @Blackarr 
Composter was added in after the Levelled class by spigot was added, and as a result does not contain blockdata in the normal form. We need to access this Levelled data instead.

**To Reproduce**
hey i run into some problems with the Composter
```
defaults:
    worlds: ALL

otherdrops:
    COMPOSTER:
        - trigger: LEFT_CLICK
          drop: DIRT
    COMPOSTER@1:
        - trigger: RIGHT_CLICK
          drop: DIRT
    COMPOSTER@2:
        - trigger: RIGHT_CLICK
          drop: DIRT
    COMPOSTER@3:
        - trigger: RIGHT_CLICK
          drop: DIRT
    COMPOSTER@4:
        - trigger: RIGHT_CLICK
          drop: DIRT
    COMPOSTER@5:
        - trigger: RIGHT_CLICK
          drop: DIRT
    COMPOSTER@RIPE:
        - trigger: RIGHT_CLICK
          drop: DIRT
```

the Left Click works fine. just the stages doesnt work. i want to have a custom drop for the Composter at the end stage

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java Version [e.g. 20]
 - Server Version [e.g. Spigot 1.20]
 - Plugin Version [e.g. 3.2.8b-180]

**Additional context**
