### ISSUE TITLE
Horse RIGHT_CLICK Trigger

### ISSUE THREAD

**Issue by Blackarr** [CoolLord22/OtherDrops1.13#37]
**Describe the bug**
RIGHT_CLICK trigger on Horses does not work

**To Reproduce**
1:   HORSE@!ADULT:
        - trigger: RIGHT_CLICK
          message: "clicked ADULT horse"
2: Right clicking Horse
3: no Message output

**Expected behavior**
There is a message output on RIGHT_CLICK

**Comment by CoolLord22** [comment]
Unable to replicate this issue; double check that you're not in creative mode perhaps?

```yaml
    HORSE@!ADULT:
        - trigger: RIGHT_CLICK
          message: "clicked ADULT horse"
```
![image](https://github.com/CoolLord22/OtherDrops1.13/assets/16751239/31e77df7-3b1d-47a9-a69b-19598ce4937d)
