### ISSUE TITLE
Actionbar | Title | Bossbar message

### ISSUE THREAD

**Issue by Achent007** [CoolLord22/OtherDrops1.13#44]
Add a parameter to select between a chat/actionbar/bossbar/title message

For bossbar : 
- color choice
- number of sections on the bar (1-6-10-12-20)
- time to be showed
- the message (with color codes)

For actionbar : 
- time to be showed
- the message (with color codes)

For titles : 
- title section
- subtitle section
- fade in timer
- keep timer
- fade out timer

**Comment by CoolLord22** [comment]
For this, should it only be shown to the player triggering the drop? Radius? Or how would we set this up?

**Comment by CoolLord22** [comment]
Implemented 3.2.8 b335, just need to do testing on it to ensure everything works as expected. All of the above was implemented except actionbar time to be showed; no method implementation exists to increase/delay how long that actionbar message is displayed for. Additionally, for bossbar added another variable for progress of the bar (0 being empty, 1.0 being full). Messages support color formatting and all [message variables](https://github.com/CoolLord22/OtherDrops1.13/wiki/Parameters#variables). Important to note, that `sendto` parameter will only be applied from 1 of the message types if multiple are selected. See usage details below:

```yaml
    ANY:
      - trigger: RIGHT_CLICK
        tool: STICK
        title:
            title: "&aTitle Line %p" # Title text
            subtitle: "&bSubtitle Line" # Subtitle text
            fadein: 10          # Time (ticks) to fade in
            stay: 70            # Time (ticks) to stay on screen
            fadeout: 10         # Time (ticks) to fade out
            sendto: ATTACKER    # Accepted values are ATTACKER, VICTIM, RADIUS, WORLD, SERVER
        actionbar:
            message: "&ctest"
            sendto: ATTACKER    # Accepted values are ATTACKER, VICTIM, RADIUS, WORLD, SERVER
        bossbar:
            message: "&ctest"
            color: RED          # Color types (see links below)
            style: SEGMENTED_20 # Segment style (see links below)
            progress: 0.5       # Supports double-type values 
            time: 10            # Time in seconds
            sendto: ATTACKER    # Accepted values are ATTACKER, VICTIM, RADIUS, WORLD, SERVER
```
- https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarColor.html
- https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/boss/BarStyle.html
![image](https://github.com/user-attachments/assets/dd34ecfc-dc14-451f-b1e6-345a30afc3fa)
