### ISSUE TITLE
fishing biom

### ISSUE THREAD

**Issue by Blackarr** [CoolLord22/OtherDrops1.13#47]
**Is your feature request related to a problem? Please describe.**
I have a fishing loottable that is other in every biom.
Riverbioms are often narrow bioms so it happens that although a player has its hook in a Riverbiom he is not Standing in it and getting other drop from a diffrent loottable.
         - trigger: FISH_CAUGHT
           drop: AIR
         - trigger: FISH_CAUGHT
           biome: RIVER
           commands: /!$craft %p RIVER
         - trigger: FISH_CAUGHT
           biome: BEACH
           commands: /!$craft %p BEACH
           ...

**Describe the solution you'd like**
It would be nice if i could get the biom of the Players hook rather then the player itself so that the lootables are always right.

simular to "potionrequirement.victim:" it could look like this:

         - trigger: FISH_CAUGHT
           biome.hook: BEACH
           drop: ...

**Comment by CoolLord22** [comment]
Opted for slightly different syntax than what was requested here; config parameters are `hookbiome`, `hookbiomes`, `fishhookbiome`, `fishhookbiomes`
```yaml
    PLAYER:
      - trigger: FISH_CAUGHT
        message: "&aCaught!" 
        fishingbiome: -sparse_jungle # biome that hook was reeled from
      - trigger: FISH_FAILED
        message: "&cFailed!"
        biome: sparse_jungle # biome that player is standing in
        fishingbiome: RIVER 
```
Supports same map type as the biome condition (ie, negative biomes, list of biomes, `ANY` keyword etc)
