### ISSUE TITLE
drop: CONTENTS filtering for items

### ISSUE THREAD

**Issue by CoolLord22** [CoolLord22/OtherDrops1.13#56]
**Is your feature request related to a problem? Please describe.**
Need a way to filter out 'filter' items from players/mobs to deny dropping them
e.g.: player had inv of stuff, including diamonds, on player_death deny the diamonds from dropping but still receive rest of items

Should ideally also have a way of doing the opposite, if a player has a bunch of items and we only want to drop a specific named 'respawn token' for example, rest of items should get denied but the specified item gets dropped.

**Describe the solution you'd like**
One possibility could be `drop: [contents, -DIAMOND]`
But realistically we want 
`contents.keep: [DIAMOND@~&bNamed Diamond]` and `contents.remove: [DIAMOND@~&bNamed Diamond]`

**Describe alternatives you've considered**
In the past I used this plugin https://dev.bukkit.org/projects/deathcontrol to filter out items from dropping (Denying them from dropping)

**Additional context**
N/A

Feature originally requested by @ImBas

**Comment by CoolLord22** [comment]
Implementation is as follows:

```yaml
  CHEST:
    - trigger: HIT
      drop: [CONTENTS]
      drops.keep: [DIAMOND@~&bNamed Diamond]
      message.server: filtering contents
  PLAYER:
    - trigger: break
      drop: [AIR, CONTENTS]
      drops.remove: [DIAMOND@~&bNamed Diamond]
    - trigger: break
      drop: DENY
```

This is largely going to be used in conjunction with CONTENTS drops specifically. 

- drops.keep means that item type is the only thing that **will drop** from all of the contents when dropping
- drops.remove means that item is the only thing that will get **removed** from the contents when dropping

Note that for the player death event specifically, you **must** also specify a drop that is set to DENY to prevent the player's items from dropping separately. This is because the player death event is never ignored and always processed independently.
